project(base_test)

# ?????? ???????? ????? (??? postfix.cpp!)
file(GLOB TEST_SOURCES "*.cpp")

add_executable(postfix_test ${TEST_SOURCES})

# ?????????? ?????????? ? gtest
target_link_libraries(postfix_test 
    base_lib   # ???? ??????????
    gtest      # Google Test
)

# ???? ? ??????????
target_include_directories(postfix_test PRIVATE
    ${CMAKE_SOURCE_DIR}/Sysoyev/base
    ${CMAKE_SOURCE_DIR}/Sysoyev/gtest
)